/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bbirze' at '3/18/16 11:47 AM' with Gradle 2.10
 *
 * @author bbirze, @date 3/18/16 11:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
